name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major'
        required: true
    branches: [ master ]

env:
  TARGET_BRANCH: test-trunk # TODO: master
  VERSION_BUMP_TYPE: ${{ github.event.inputs.release-type }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '20'
      - run: npm ci
      - run: npm run build
      
      - name: Git configuration
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - run: npm version ${{ env.VERSION_BUMP_TYPE }}
      - run: git log -2
      - name: Push changes to remote branch ${{ env.TARGET_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push --tags origin HEAD:"$TARGET_BRANCH"
      - run: npm pack --dry-run
