name: Node.js compatibility (CLI)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        id: nvmrc-reader
        run: echo "NVMRC=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvmrc-reader.outputs.NVMRC }}'

      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  test-cli:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version:
          - 12.13.x
          - 14.x
          - 16.x
          - 18.x
          - 20.x

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci --ignore-scripts
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - run: npm run test-cli
