# This workflow will do a clean install of node dependencies, build the source code and run tests

# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and test (Node.js)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        id: nvmrc-reader
        run: echo "NVMRC=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvmrc-reader.outputs.NVMRC }}'

      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          CI: true
